language: emacs-lisp
before_install:
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.4-bin
script:
  make travis-ci
